---
title: "First Knit"
author: "Kathleen Castro"
date: "`r Sys.Date()`"
output:
  pdf_document:
    toc: yes
    toc_depth: '5'
  html_document:
    number_sections: yes
    toc: yes
    toc_depth: 5
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare english class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.  
  
### my answer     
I attended Lancaster High School. I did indeed graduate. I find English to be easier than Math. English has been easier for me to understand compared to mathematics. My skills fall heavily upon English and any scientific subjects. Perhaps leaning more on Biology.

     


## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

### my answer   
I have a Lenovo Laptop. I would rate my computer skills somewhere between 6 or 7. My internet connection seems to be stable and works well.

   

## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

### my answer     
  
I'm okay with being called Kathleen, but I have also been given a nickname that tends to be easier. Some people call me Kat.




## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer     
  

I'm still pretty uncertain on what I want to achieve specifically in life, but having a stable job with good income wouldn't be so bad. The subject I find the most interest in is Biology. I'm aiming for a Master's degree. 
   
 




## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer     
  
No, I have not visited any foreign countries. Places I do wish to visit would be London, New Zeland,Germany and Paris. No I have not been part of the military. I would prefer not to join it, but if I were to get drafted I would join the Marines.   
  




## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### my answer     
  
I did not take Math 115, but I am taking Math 116. I did know about this information, but I wasn't provided with it as I had to research thoroughly on what classes were necessary for transfer. I hope to obtain a passing grade with an A or B. 
 






  




